---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  selector:
    matchLabels:
      app: frontend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      nodeSelector:
        kubernetes.azure.com/mode: user
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: frontend-app
          image: containerrepoakstest.azurecr.io/frontend-app:SET_TAG_IN_OVERLAY
          command: ["npm"]
          args: ["run", "server"]
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
              cpu: "500m"
            requests:
              memory: 512Mi
              cpu: "500m"
