apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../bases/node-app

images:
- name: containerrepoakstest.azurecr.io/node-app
  newTag: "1"

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: node-app
    path: replace_ingress_host.jsonpatch.yaml