apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../bases/frontend-app

images:
- name: containerrepoakstest.azurecr.io/frontend-app
  newTag: "4-dev"

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: frontend-app
    path: replace_ingress_host.jsonpatch.yaml